// <auto-generated />
using System;
using EnrolledManagementSystem.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnrolledManagementSystem.Migrations
{
    [DbContext(typeof(ManagementDbContext))]
    [Migration("20241114031108_AddTable_LoaiHocPhi_PhieuThuHP")]
    partial class AddTable_LoaiHocPhi_PhieuThuHP
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EnrolledManagementSystem.Entities.GiangVien", b =>
                {
                    b.Property<string>("MaGiangVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaMonDayChinh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MonDayKiemNhiem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("TenDemVaTen")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("MaGiangVien");

                    b.HasIndex("MaMonDayChinh");

                    b.ToTable("GiangVien");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.HocVien", b =>
                {
                    b.Property<string>("MaHocVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HoTenPhuHuynh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaLopHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("TenDemVaTen")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("MaHocVien");

                    b.HasIndex("MaLopHoc");

                    b.ToTable("HocVien");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhoa");

                    b.ToTable("Khoa");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.Khoa_Khoi", b =>
                {
                    b.Property<string>("MaKhoaKhoi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenKhoaKhoi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaKhoaKhoi");

                    b.ToTable("Khoa_Khoi");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.LoaiDiem", b =>
                {
                    b.Property<string>("MaLoaiDiem")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("HeSo")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiDiem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoaiDiem");

                    b.ToTable("LoaiDiem");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.LoaiDiemMon", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaMon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoCotDiem")
                        .HasColumnType("int");

                    b.Property<int>("SoCotDiemBatBuoc")
                        .HasColumnType("int");

                    b.HasKey("MaKhoa", "MaMon", "MaLoai");

                    b.HasIndex("MaLoai");

                    b.HasIndex("MaMon");

                    b.ToTable("LoaiDiemMon");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.LoaiHocPhi", b =>
                {
                    b.Property<string>("MaLoaiHocPhi")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenLoaiHocPhi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoaiHocPhi");

                    b.ToTable("LoaiHocPhi");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.LopHoc", b =>
                {
                    b.Property<string>("MaLop")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("HocPhi")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MaKhoaKhoi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaNienKhoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuongHocVien")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaKhoaKhoi");

                    b.HasIndex("MaNienKhoa");

                    b.ToTable("LopHoc");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.MonHoc", b =>
                {
                    b.Property<string>("MaMonHoc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaKhoaKhoi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("MaToBoMon")
                        .HasColumnType("int");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaMonHoc");

                    b.HasIndex("MaKhoaKhoi");

                    b.HasIndex("MaToBoMon");

                    b.ToTable("MonHoc");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.NienKhoa", b =>
                {
                    b.Property<string>("MaNienKhoa")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenNienKhoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaNienKhoa");

                    b.ToTable("NienKhoa");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.PhanCongGiangDay", b =>
                {
                    b.Property<string>("MaLopHoc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaMonHoc")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaGiangVien")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("GioBatDau")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioKetThuc")
                        .HasColumnType("time");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("date");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("date");

                    b.Property<string>("PhongHoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Thu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLopHoc", "MaMonHoc", "MaGiangVien");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaMonHoc");

                    b.ToTable("PhanCongGiangDay");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.PhieuThuHocPhi", b =>
                {
                    b.Property<string>("MaPhieu")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("GiamGia")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("MaLoaiHocPhi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MaLop")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Mota")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("MucThuPhi")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("NgayTao")
                        .HasMaxLength(20)
                        .HasColumnType("datetime2");

                    b.HasKey("MaPhieu");

                    b.HasIndex("MaLoaiHocPhi");

                    b.HasIndex("MaLop");

                    b.ToTable("PhieuThuHocPhi");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.To_BoMon", b =>
                {
                    b.Property<int>("MaToBoMon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaToBoMon"), 1L, 1);

                    b.Property<string>("TenToBoMon")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaToBoMon");

                    b.ToTable("To_BoMon");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.GiangVien", b =>
                {
                    b.HasOne("EnrolledManagementSystem.Entities.MonHoc", "MonChinh")
                        .WithMany("giangViens")
                        .HasForeignKey("MaMonDayChinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonChinh");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.HocVien", b =>
                {
                    b.HasOne("EnrolledManagementSystem.Entities.LopHoc", "LopHoc")
                        .WithMany("hocViens")
                        .HasForeignKey("MaLopHoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.LoaiDiemMon", b =>
                {
                    b.HasOne("EnrolledManagementSystem.Entities.Khoa", "Khoa")
                        .WithMany("loaiDiemMons")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnrolledManagementSystem.Entities.LoaiDiem", "LoaiDiem")
                        .WithMany("loaiDiemMons")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnrolledManagementSystem.Entities.MonHoc", "MonHoc")
                        .WithMany("loaiDiemMons")
                        .HasForeignKey("MaMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");

                    b.Navigation("LoaiDiem");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.LopHoc", b =>
                {
                    b.HasOne("EnrolledManagementSystem.Entities.Khoa_Khoi", "Khoa_Khoi")
                        .WithMany("lopHocs")
                        .HasForeignKey("MaKhoaKhoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnrolledManagementSystem.Entities.NienKhoa", "NienKhoa")
                        .WithMany("lopHocs")
                        .HasForeignKey("MaNienKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa_Khoi");

                    b.Navigation("NienKhoa");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.MonHoc", b =>
                {
                    b.HasOne("EnrolledManagementSystem.Entities.Khoa_Khoi", "Khoa_Khoi")
                        .WithMany("monHocs")
                        .HasForeignKey("MaKhoaKhoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnrolledManagementSystem.Entities.To_BoMon", "To_BoMon")
                        .WithMany("monHocs")
                        .HasForeignKey("MaToBoMon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa_Khoi");

                    b.Navigation("To_BoMon");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.PhanCongGiangDay", b =>
                {
                    b.HasOne("EnrolledManagementSystem.Entities.GiangVien", "GiangVien")
                        .WithMany("phanCongGiangDays")
                        .HasForeignKey("MaGiangVien")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EnrolledManagementSystem.Entities.LopHoc", "LopHoc")
                        .WithMany("phanCongGiangDays")
                        .HasForeignKey("MaLopHoc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("EnrolledManagementSystem.Entities.MonHoc", "MonHoc")
                        .WithMany("phanCongGiangDays")
                        .HasForeignKey("MaMonHoc")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GiangVien");

                    b.Navigation("LopHoc");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.PhieuThuHocPhi", b =>
                {
                    b.HasOne("EnrolledManagementSystem.Entities.LoaiHocPhi", "LoaiHocPhi")
                        .WithMany("phieuThuHocPhis")
                        .HasForeignKey("MaLoaiHocPhi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EnrolledManagementSystem.Entities.LopHoc", "LopHoc")
                        .WithMany("phieuThuHocPhis")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHocPhi");

                    b.Navigation("LopHoc");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.GiangVien", b =>
                {
                    b.Navigation("phanCongGiangDays");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.Khoa", b =>
                {
                    b.Navigation("loaiDiemMons");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.Khoa_Khoi", b =>
                {
                    b.Navigation("lopHocs");

                    b.Navigation("monHocs");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.LoaiDiem", b =>
                {
                    b.Navigation("loaiDiemMons");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.LoaiHocPhi", b =>
                {
                    b.Navigation("phieuThuHocPhis");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.LopHoc", b =>
                {
                    b.Navigation("hocViens");

                    b.Navigation("phanCongGiangDays");

                    b.Navigation("phieuThuHocPhis");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.MonHoc", b =>
                {
                    b.Navigation("giangViens");

                    b.Navigation("loaiDiemMons");

                    b.Navigation("phanCongGiangDays");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.NienKhoa", b =>
                {
                    b.Navigation("lopHocs");
                });

            modelBuilder.Entity("EnrolledManagementSystem.Entities.To_BoMon", b =>
                {
                    b.Navigation("monHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
